services:
  web:
    container_name: webapp-test
    build:
      context: ../
      dockerfile: docker/Dockerfile
    volumes:
      - '../:/app'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=production
