name: Deploy to AWS

on:
  workflow_run:
    workflows: ["Build and publish"]
    types: [completed]

jobs:
  on-success:

    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: AWS SSM Send-Command
        run: |
          export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}; export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }};
          aws ssm send-command \
          --instance-ids ${{ secrets.AWS_INSTANCE_ID }} \
          --region ${{ secrets.AWS_REGION }}
          --document-name "AWS-RunShellScript" \
          --parameters "commands=['sudo systemctl stop docker-application', 'sudo docker pull ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:latest', 'sudo systemctl start docker-application']” \
          --output text \
          --query Command.CommandId | \
          xargs aws ssm wait command-executed \
          --command-id $1 \
          --instance-id ${{ secrets.AWS_INSTANCE_ID }}
