name: Deploy to AWS

on:
  workflow_run:
    workflows: ["Build and publish"]
    types: [completed]

jobs:
  on-success:

    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Configure aws settings
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region ${{ secrets.AWS_REGION }}

      - name: AWS SSM Send-Command
        run: |
          DOCKER_IMAGE="ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}"
          DOCKER_IMAGE_LOWERCASE="${DOCKER_IMAGE,,}"
          RESULT="$(aws ssm send-command \
          --instance-ids ${{ secrets.AWS_INSTANCE_ID }} \
          --document-name AWS-RunShellScript \
          --parameters "commands=['cd /home/ubuntu', './deploy.sh']" \
          --output text \
          --query Command.CommandId)"
          echo "SSM_COMMAND_ID=$RESULT" >> $GITHUB_ENV
      - name: Wait for SSM Command to finish
        run: |
          echo "Command ID: $SSM_COMMAND_ID"
          aws ssm wait command-executed \
          --command-id $SSM_COMMAND_ID \
          --instance-id ${{ secrets.AWS_INSTANCE_ID }}
        env:
          SSM_COMMAND_ID: ${{ env.SSM_COMMAND_ID }}
