name: Deploy to AWS

on:
  workflow_run:
    workflows: ["Build and publish"]
    types: [completed]

jobs:
  on-success:

    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: AWS SSM Send-Command
        uses: peterkimzz/aws-ssm-send-command@v1.1.1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          instance-ids: ${{ secrets.AWS_INSTANCE_ID }}
          working-directory: /home/ubuntu
          command: |
            sudo systemctl stop docker-application
            sudo docker pull ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:latest
            sudo systemctl start docker-application

          comment: docker-compose.yml file re-pulls newer versions of deployed image and runs them on the instance.
